# Generated by Django 4.1.7 on 2023-05-11 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rounds', '0001_initial'),
        ('teams', '0002_alter_team_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('match_date', models.DateTimeField()),
                ('away_team', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rounds.round')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
