# Generated by Django 4.1.7 on 2023-05-14 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_away_goals_alter_match_home_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_team',
            new_name='away_team_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_team',
            new_name='home_team_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='round',
            new_name='round_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
