# Generated by Django 4.1.7 on 2023-05-11 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name_plural': 'Teams'},
        ),
    ]
